CREATE TABLE IF NOT EXISTS doctor (
    id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    firstname varchar(255) not null,
    surname varchar(255) not null,
    patronymic varchar(255) not null,
    specialization varchar(255) not null
)

CREATE TABLE IF NOT EXISTS pacient (
    id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    firstname varchar(255) not null,
    surname varchar(255) not null,
    patronymic varchar(255) not null,
    phone integer
)

CREATE TABLE IF NOT EXISTS recipe (
    id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    creation date not null,
    description varchar(255) not null,
    exposure date not null,
    priority varchar(255) not null,
    doctor_id integer not null,
    pacient_id integer not null,
    pacient varchar(510),
    doctor varchar(50)
)
--ALTER TABLE recipe ALTER COLUMN priority TYPE AS ENUM('Normal', 'Cito', 'Statim');
--CREATE type priority as enum ('Normal', 'Cito', 'Statim');
ALTER TABLE recipe ADD FOREIGN KEY (id_recipe) REFERENCES pacient(id_pacient);
ALTER TABLE recipe ADD FOREIGN KEY (id_recipe) REFERENCES doctor(id_doctor);
